-- Database Initialization Script
-- Generated by ProjexLight CLI Export System
-- Project: Ride Share
-- Database: postgresql
-- Auto-executed when Docker container is first created
-- Location: ./init-scripts/01-create-schema.sql
-- Schema Hash: e10808d43975dc40

-- ========================================
-- SCHEMA VERSION TRACKING (For Multi-Developer Sync)
-- ========================================
-- This table tracks the current schema version in your local database.
-- The MCP Schema Sync Agent uses this to detect changes and sync with ProjexLight.

CREATE TABLE IF NOT EXISTS _schema_version (
    id SERIAL PRIMARY KEY,
    schema_hash VARCHAR(64) NOT NULL,
    version INTEGER DEFAULT 1,
    applied_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    source VARCHAR(50) DEFAULT 'init'  -- 'init', 'migration', 'sync'
);

-- ========================================
-- APPLICATION SCHEMA
-- ========================================

-- User-Defined Database Schemas
-- Generated by ProjexLight CLI Export System
-- Database: postgresql
-- Total Schemas: 1

-- ========================================
-- Schema: Ride Share Schema
-- Description: Auto-generated database schema for Ride Share. Generated from project description...
-- Version: 1
-- ========================================

CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email VARCHAR(255),
  password_hash VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE users IS 'Schema: Ride Share Schema - Entity: Users';

CREATE TABLE IF NOT EXISTS user_profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID,
  preferences JSONB DEFAULT '"{}"'::JSONB,
  trip_history JSONB DEFAULT '"{}"'::JSONB,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE user_profiles IS 'Schema: Ride Share Schema - Entity: User_profiles';

CREATE TABLE IF NOT EXISTS user_feedback (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  feedback_id UUID,
  user_id UUID,
  rating INTEGER,
  comments TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE user_feedback IS 'Schema: Ride Share Schema - Entity: User_feedback';

CREATE TABLE IF NOT EXISTS trips (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  trip_id UUID,
  user_id UUID,
  destination VARCHAR(255),
  departure_time TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE trips IS 'Schema: Ride Share Schema - Entity: Trips';

CREATE TABLE IF NOT EXISTS matched_trips (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  match_id UUID,
  trip_id UUID,
  user_id UUID,
  matched_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE matched_trips IS 'Schema: Ride Share Schema - Entity: Matched_trips';

CREATE TABLE IF NOT EXISTS trip_history (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  history_id UUID,
  user_id UUID,
  trip_id UUID,
  completed_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE trip_history IS 'Schema: Ride Share Schema - Entity: Trip_history';

CREATE TABLE IF NOT EXISTS payments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  payment_id UUID,
  user_id UUID,
  amount DECIMAL(10,2),
  payment_status VARCHAR(255) DEFAULT 'pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE payments IS 'Schema: Ride Share Schema - Entity: Payments';

CREATE TABLE IF NOT EXISTS billing_history (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  billing_id UUID,
  user_id UUID,
  payment_id UUID,
  billing_date TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE billing_history IS 'Schema: Ride Share Schema - Entity: Billing_history';

CREATE TABLE IF NOT EXISTS refunds (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  refund_id UUID,
  user_id UUID,
  payment_id UUID,
  status VARCHAR(255) DEFAULT 'pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE refunds IS 'Schema: Ride Share Schema - Entity: Refunds';


-- ========================================
-- SAMPLE DATA (Optional)
-- ========================================
-- Uncomment and modify the following to add sample data:

-- INSERT INTO users (column1, column2) VALUES ('value1', 'value2');
-- INSERT INTO user_profiles (column1, column2) VALUES ('value1', 'value2');
-- INSERT INTO user_feedback (column1, column2) VALUES ('value1', 'value2');
-- INSERT INTO trips (column1, column2) VALUES ('value1', 'value2');
-- INSERT INTO matched_trips (column1, column2) VALUES ('value1', 'value2');
-- INSERT INTO trip_history (column1, column2) VALUES ('value1', 'value2');
-- INSERT INTO payments (column1, column2) VALUES ('value1', 'value2');
-- INSERT INTO billing_history (column1, column2) VALUES ('value1', 'value2');
-- INSERT INTO refunds (column1, column2) VALUES ('value1', 'value2');

-- ========================================
-- RECORD INITIAL SCHEMA VERSION
-- ========================================
INSERT INTO _schema_version (schema_hash, version, source) VALUES ('e10808d43975dc40', 1, 'init');

-- ========================================
-- SCRIPT COMPLETED
-- ========================================
