-- Database Initialization Script
-- Generated by ProjexLight CLI Export System
-- Project: Log Analysis
-- Database: postgresql
-- Auto-executed when Docker container is first created
-- Location: ./init-scripts/01-create-schema.sql
-- Schema Hash: e10808d43975dc40

-- ========================================
-- SCHEMA VERSION TRACKING (For Multi-Developer Sync)
-- ========================================
-- This table tracks the current schema version in your local database.
-- The MCP Schema Sync Agent uses this to detect changes and sync with ProjexLight.

CREATE TABLE IF NOT EXISTS _schema_version (
    id SERIAL PRIMARY KEY,
    schema_hash VARCHAR(64) NOT NULL,
    version INTEGER DEFAULT 1,
    applied_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    source VARCHAR(50) DEFAULT 'init'  -- 'init', 'migration', 'sync'
);

-- ========================================
-- APPLICATION SCHEMA
-- ========================================

-- User-Defined Database Schemas
-- Generated by ProjexLight CLI Export System
-- Database: postgresql
-- Total Schemas: 1

-- ========================================
-- Schema: Log Analysis Schema
-- Description: Auto-generated database schema for Log Analysis. Generated from project description...
-- Version: 1
-- ========================================

CREATE TABLE IF NOT EXISTS cloudwatch_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  timestamp TIMESTAMP WITH TIME ZONE,
  message TEXT,
  log_level VARCHAR(255),
  service_name VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE cloudwatch_logs IS 'Schema: Log Analysis Schema - Entity: Cloudwatch_logs';

CREATE TABLE IF NOT EXISTS slack_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  channel VARCHAR(255),
  message TEXT,
  timestamp TIMESTAMP WITH TIME ZONE,
  user_id VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE slack_logs IS 'Schema: Log Analysis Schema - Entity: Slack_logs';

CREATE TABLE IF NOT EXISTS custom_app_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  timestamp TIMESTAMP WITH TIME ZONE,
  log_content TEXT,
  application_name VARCHAR(255),
  log_type VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE custom_app_logs IS 'Schema: Log Analysis Schema - Entity: Custom_app_logs';

CREATE TABLE IF NOT EXISTS aggregated_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  source VARCHAR(255),
  aggregated_message TEXT,
  aggregated_timestamp TIMESTAMP WITH TIME ZONE,
  log_count INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE aggregated_logs IS 'Schema: Log Analysis Schema - Entity: Aggregated_logs';

CREATE TABLE IF NOT EXISTS extracted_params (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  log_id UUID,
  parameter_name VARCHAR(255),
  parameter_value TEXT,
  extraction_timestamp TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE extracted_params IS 'Schema: Log Analysis Schema - Entity: Extracted_params';

CREATE TABLE IF NOT EXISTS user_interface (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(255),
  status VARCHAR(255) DEFAULT 'active',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE user_interface IS 'Schema: Log Analysis Schema - Entity: User_interface';


-- ========================================
-- SAMPLE DATA (Optional)
-- ========================================
-- Uncomment and modify the following to add sample data:

-- INSERT INTO cloudwatch_logs (column1, column2) VALUES ('value1', 'value2');
-- INSERT INTO slack_logs (column1, column2) VALUES ('value1', 'value2');
-- INSERT INTO custom_app_logs (column1, column2) VALUES ('value1', 'value2');
-- INSERT INTO aggregated_logs (column1, column2) VALUES ('value1', 'value2');
-- INSERT INTO extracted_params (column1, column2) VALUES ('value1', 'value2');
-- INSERT INTO user_interface (column1, column2) VALUES ('value1', 'value2');

-- ========================================
-- RECORD INITIAL SCHEMA VERSION
-- ========================================
INSERT INTO _schema_version (schema_hash, version, source) VALUES ('e10808d43975dc40', 1, 'init');

-- ========================================
-- SCRIPT COMPLETED
-- ========================================
