-- User-Defined Database Schemas
-- Generated by ProjexLight CLI Export System
-- Database: postgresql
-- Total Schemas: 1

-- ========================================
-- Schema: Log Analysis Schema
-- Description: Auto-generated database schema for Log Analysis. Generated from project description...
-- Version: 1
-- ========================================

CREATE TABLE IF NOT EXISTS cloudwatch_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  timestamp TIMESTAMP WITH TIME ZONE,
  message TEXT,
  log_level VARCHAR(255),
  service_name VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE cloudwatch_logs IS 'Schema: Log Analysis Schema - Entity: Cloudwatch_logs';

CREATE TABLE IF NOT EXISTS slack_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  channel VARCHAR(255),
  message TEXT,
  timestamp TIMESTAMP WITH TIME ZONE,
  user_id VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE slack_logs IS 'Schema: Log Analysis Schema - Entity: Slack_logs';

CREATE TABLE IF NOT EXISTS custom_app_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  timestamp TIMESTAMP WITH TIME ZONE,
  log_content TEXT,
  application_name VARCHAR(255),
  log_type VARCHAR(255),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE custom_app_logs IS 'Schema: Log Analysis Schema - Entity: Custom_app_logs';

CREATE TABLE IF NOT EXISTS aggregated_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  source VARCHAR(255),
  aggregated_message TEXT,
  aggregated_timestamp TIMESTAMP WITH TIME ZONE,
  log_count INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE aggregated_logs IS 'Schema: Log Analysis Schema - Entity: Aggregated_logs';

CREATE TABLE IF NOT EXISTS extracted_params (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  log_id UUID,
  parameter_name VARCHAR(255),
  parameter_value TEXT,
  extraction_timestamp TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE extracted_params IS 'Schema: Log Analysis Schema - Entity: Extracted_params';

CREATE TABLE IF NOT EXISTS user_interface (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name VARCHAR(255),
  status VARCHAR(255) DEFAULT 'active',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE user_interface IS 'Schema: Log Analysis Schema - Entity: User_interface';

